anyscale/templates

templates/image-classification-service/trt-resnet.py

Importing tensorrt outside the actor fails when using serve deploy since it requires GPU

Update import in trt-resnet.py

---

templates/endpoints/models/HuggingFaceH4--zephyr-7b-beta.yaml
templates/endpoints/models/Meta-Llama--LlamaGuard-7b-hf.yaml
templates/endpoints/models/codellama--CodeLlama-34b-Instruct-hf.yaml
templates/endpoints/models/meta-llama--Llama-2-13b-chat-hf.yaml
templates/endpoints/models/meta-llama--Llama-2-70b-chat-hf.yaml
templates/endpoints/models/meta-llama--Llama-2-7b-chat-hf_a10-lora.yaml
templates/endpoints/models/meta-llama--Llama-2-7b-chat-hf_a10.yaml
templates/endpoints/models/mistralai--Mistral-7B-Instruct-v0.1.yaml

This parameter is removed in vllm engine in upcoming versions

Remove enable_custom_nccl config

---

templates/endpoints/README.md

- Added notes for service url
- Aida from Handshake ran into this issue and didn't know that she needed to add `/v1` in the path

[Endpoints] Added notes for service url

---

templates/endpoints/models/meta-llama--Llama-2-7b-chat-hf_a10-lora.yaml

Added new configs for lora and tested this is compatible with our llama lora checkpoints as well

add new lora configs

---

configs/serve-stable-diffusion/gce.yaml

Add gce yaml in case something goes wrong because of its absence.

Add gce.yaml

---

templates/serve-stable-diffusion/README.ipynb

- Add an ipynb notebook to unblock @sofianhnaide 
- This isn't fully fleshed out yet, will update with @edoakes 's new stuff in a separate PR

Add ipynb version of stable diffusion template

---

templates/fine-tune-llm/README.md
templates/fine-tune-llm/train.py

- Added the new llmforge CLI option that allows multi serving
- This should not be enabled for customers unless the prod deployment has the latest llmforge

[FT-Lora] Added lora instructions

---

templates/fine-tune-llm/README.md
templates/fine-tune-llm/job_compute_configs/gcp.yaml

- Updated the template with more info on lora finetuning and serving
- Currently users have no easy way of getting fientuend lora model ID.
- TODO: the model ID should be outputted directly in the logs. I will get to this after I come back from vacation

[FT] Updated the template

---

templates/fine-tune-llm/train.py

This is needed to be compatible with llm-forge:0.4.1.3. https://github.com/anyscale/llm-forge/pull/287
**CAUTION**
Merge this only after [Product PR is merged and deployed to production](https://github.com/anyscale/product/pull/26495/files).

Finetune template : Generate model tags and pass to llm-forge

---

configs/rag-dev-bootcamp-mar2024/aws.yaml
configs/rag-dev-bootcamp-mar2024/gce.yaml

Remove auto_select_worker_config from RAG Bootcamp Template

---

templates/serve-stable-diffusion/main.py

Tested manually in notebook. Overall, the quality seems much higher and the speed is pretty similar.
```
image = generate_image("Anyscale logo, as a valentines day card, professional quality art, surrounded by flowers with white envelope background", 640)
filename = "image.png"
with open(filename, "wb") as f:
f.write(image)
from IPython.display import Image
Image(filename=filename)
```

Upgrade stable diffusion OA template to SDXL

---

templates/intro-batch-inference/README.ipynb
templates/intro-batch-inference/README.md
templates/intro-workspaces/README.ipynb
templates/intro-workspaces/README.md

- Device seems to be an int now
- Code sample for asserting batch wasn't properly run before

Fix some crashes in OA batch inference template due to transformers upgrade

---

templates/endpoints/llm-serve.yaml
templates/endpoints_v2/llm-serve.yaml

Temporary workaround for: https://github.com/anyscale/ray-llm/issues/1423

[llm] Add empty lists to satisfy private endpoints model validation

---

templates/intro-batch-inference/README.ipynb
templates/intro-batch-inference/README.md

- Add a example using 100k rows
- Note I had to manually repartition the dataset in this case (@raulchen will this be fixed for GA?)

[OA] Improve batch inference example by adding a scaling example

---

templates/rag-dev-bootcamp-mar2024/README.md

Add a Get Started section to the RAG Dev Bootcamp README

add get started section to RAG Dev Bootcamp README

---

templates/rag-dev-bootcamp-mar2024/README.md

RAG Dev Bootcamp - add agenda to the README

---

configs/getting-started/aws.yaml
configs/getting-started/gce.yaml
templates/getting-started/README.ipynb
templates/getting-started/README.md

This is adding the getting-started template.

getting started

---

templates/endpoints_v2/README.ipynb
templates/endpoints_v2/README.md

- Confused about URL
- Add error check

[OA] Fix user gotchas in endpoint v2

---

templates/endpoints/models/llama/meta-llama--Llama-2-13b-chat-hf_a100-40g_tp4-lora.yaml

Endpoints template: Add long context yaml

---

templates/fine-tune-llm/job_compute_configs/aws.yaml
templates/fine-tune-llm/job_compute_configs/gcp.yaml

- Removed multi-zone config for training jobs
- thread: https://anyscaleteam.slack.com/archives/CKRJJNN4E/p1710635724823809

[Template] Removed multi-zone config for training jobs

---

ci/auto-generate-readme.sh
templates/batch-llm/README.md
templates/intro-workspaces/README.md

This is causing build failures for https://github.com/anyscale/endpoint-docs/pull/124

[OA] Fix generated md files including md image syntax

---

templates/intro-workspaces/README.ipynb
templates/intro-workspaces/README.md

- Clarify persistence of project dir
- Add link to docs

[OA] Clarify exactly what is persisted and limited

---

templates/text-embeddings/README.md

generate md form of https://github.com/anyscale/templates/pull/164/files

[OA] [minor] Forgot to run conversion script

---

templates/intro-workspaces/README.ipynb
templates/intro-workspaces/README.md

- Add example for how to use cluster env vars

[OA] Add cluster env vars doc to intro workspace template

---

templates/endpoints_v2/README.ipynb
templates/endpoints_v2/README.md
templates/endpoints_v2/examples/CustomModels.ipynb
templates/endpoints_v2/models/llama/meta-llama--Llama-2-13b-chat-hf_a100-40g_tp2.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-70b-chat-hf_a100-80g_tp8.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-7b-chat-hf_a10g_tp1.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-7b-chat-hf_l4_tp1.yaml
templates/endpoints_v2/models/mistral/mistralai--Mistral-7B-Instruct-v0.1_l4_tp2.yaml
templates/endpoints_v2/models/mistral/mistralai--Mixtral-8x7B-Instruct-v0.1_a100-80g_tp8.yaml

Reverts anyscale/templates#151
The template should be merged after either https://github.com/anyscale/product/pull/27581 or https://github.com/anyscale/product/pull/27369.

Revert "[Endpoints] Updated the endpoints template to have an easier starting UX"

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md
templates/batch-llm/main.py

Update `batch-llm` workspace template to support LLaMA 3 8B model.
Also update the login method for getting Hugging Face token, so that we only do it if the model requires it. We first check this by loading the AutoConfig for the model, which will fail if a token is required. In this case, we trigger the authentication via VS Code overlay.
Tested on [workspace](https://console.anyscale-staging.com/v2/cld_kvedZWag2qA8i5BjxUevf5i7/workspaces/expwrk_jiit4ufssay8fkw1wfvv5tp744/ses_531agcuc51q5m2l3nvrzqjiwcj?workspace-tab=vscode)

Add LLaMA 3 on `batch-llm` template

---

templates/endpoints_v2/README.ipynb
templates/endpoints_v2/README.md

- Mistral recently gated their repos such that HF token is needed

Added token setup to example commands

---

templates/endpoints_v2/models/dbrx/databricks--dbrx-instruct_a100-80g_tp8.yaml

Adds a DBRX endpoints template using OSS vLLM.

Add DBRX endpoints template

---

templates/batch-llm/util/utils.py
templates/fine-tune-llm/main.py
templates/fine-tune-llm_v2/main.py
templates/text-embeddings/util/utils.py

Slight simplification on the existing code since we need multiple

[cleanup] Replace random.choice with random.choices

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md
templates/intro-jobs/README.ipynb
templates/intro-jobs/README.md
templates/text-embeddings/README.ipynb
templates/text-embeddings/README.md

Same as https://github.com/anyscale/templates/pull/192

s/ray job submit/anyscale job submit

---

templates/endpoints/models/mistral/mistralai--Mistral-7B-Instruct-v0.1_a10g_tp1-lora.yaml
templates/endpoints_v2/models/mistral/mistralai--Mistral-7B-Instruct-v0.1_a10g_tp1-lora.yaml
templates/endpoints_v2/models/mistral/mistralai--Mistral-7B-Instruct-v0.1_l4_tp1-lora.yaml

This lead to errors when running.

Remove spec decode from LoRA yamls (not supported)

---

templates/fine-tune-llm_v2/training_configs/full_param/llama-3-70b.yaml
templates/fine-tune-llm_v2/training_configs/full_param/llama-3-8b.yaml
templates/fine-tune-llm_v2/training_configs/full_param/mistral-7b.yaml
templates/fine-tune-llm_v2/training_configs/full_param/mixtral-8x7b.yaml
templates/fine-tune-llm_v2/training_configs/lora/llama-3-70b.yaml
templates/fine-tune-llm_v2/training_configs/lora/llama-3-8b.yaml
templates/fine-tune-llm_v2/training_configs/lora/mistral-7b.yaml
templates/fine-tune-llm_v2/training_configs/lora/mixtral-8x7b.yaml

@SumanthRH flagged to me that our learning rates on the templates are lower. We have been having a too low learning rate on the templates all along.
Thanks @SumanthRH 
Some context on learning rates from instacart workload. TLDR: 1e-4 is a good number.
https://anyscaleteam.slack.com/archives/C035J1Z5EUB/p1711132679445679?thread_ts=1710815945.855269&cid=C035J1Z5EUB

Update LoRA learning rates

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md
templates/batch-llm/util/utils.py

- Add details about customizing `LLM` instance
- Update path where Hugging Face token is saved on workspace
Video walkthrough of template:
https://github.com/anyscale/templates/assets/5122851/d77455db-8533-49ad-98f6-64885b0d9922

Add customization details, update token path for `batch-llm` template

---

templates/text-embeddings/README.ipynb
templates/text-embeddings/README.md

The image needs a self-enclosing tag to render correctly.

Self-enclosing tag fix

---

templates/endpoints_v2/README.ipynb
templates/endpoints_v2/README.md

- Updated command to non-jupyter cell since this command is interactive and doesn't work under jupyter notebook cell

[LLM Serving Template] Updated command to non-jupyter cell

---

.github/CODEOWNERS

Add Docs team to codeowners for templates/

Add Docs team to CODEOWNERS for templates/

---

.github/CODEOWNERS

- Replace Yifei/Eric with @sofianhnaide / @scottsun94 
- Remove @emmyscode on her request

[Codeowner] Fix codeowners file

---

templates/fine-tune-llm_v2/training_configs/full_param/llama-3-70b.yaml
templates/fine-tune-llm_v2/training_configs/lora/llama-3-70b.yaml

- Updated template model names

Updated template model names

---

templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-function-calling/README.ipynb
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-function-calling/README.md
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-function-calling/fc_utils/eval_data_utils.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-function-calling/fc_utils/preprocessing.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-function-calling/fc_utils/response_parsers.py

Removing reference to endpoints

[ft-templates] Remove references to endpoints in the finetuning templates

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md
templates/intro-batch-inference/README.ipynb
templates/intro-batch-inference/README.md
templates/intro-jobs/README.ipynb
templates/intro-jobs/README.md
templates/intro-tune/README.ipynb
templates/intro-tune/README.md
templates/text-embeddings/README.ipynb
templates/text-embeddings/README.md

rather than "is run within a workspace"

grammar: "runs within a workspace"

---

templates/endpoints_v2/generate_config.py

There was a refactoring done recently that breaks this.

[RayLLM] Fixed generate_config.py

---

templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/summary_generation/gpt4o_eval.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/summary_generation/mistral_finetuned_eval.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/summary_generation/mistral_reference_eval.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/summary_generation/mistral_training_data.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/generate_dpo_data.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/generate_questions.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/generate_summaries.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/generate_summaries_and_scores.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/get_eval_stats.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/models.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/synthetic_data_utils.py
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/utils/utils.py

Completely rewritees DPO summary generation.
Adds some helpful abstractions for online and offline inference and also adds Pydantic models to expose a clean config to the user. 
User interface is now:
`python -m utils.generate_summaries /path/to/config.yaml`

DPO Generate Summary Rewrite

---

templates/fine-tune-llm_v2/README.ipynb
templates/fine-tune-llm_v2/README.md

Updates links to documentation in `llmforge` . Also, I noticed that there are merge conflicts between `release_branch` and `main` in #292  for reasons I don't completely understand (we've always kept this branch to track `main` directly). The only way to fix this is to merge changes from release branch into `main` and then merge `main` into the release branch. So this PR also does that.

[ft-template] update doc links

---

.github/workflows/pre-commit.yaml

so that they do not easily break due to Internet changes

[ci] pin python and package versions

---

ci/go.mod
ci/go.sum
ci/maketmpl/template.go
ci/maketmpl/template_test.go

this yaml file defines templates/apps to be built
in contains the meta data, the directory and
have pointers to the compute configs
this is part of the process to make template build artifacts self-containing

[maketmpl] add template definition yaml file

---

ci/maketmpl/util.go
ci/maketmpl/util_test.go

used in building template/app zip files

[maketmpl] add util function and test

---

ci/maketmpl/util.go
ci/maketmpl/util_test.go

from a list of files. will use this to build template release artifacts

[maketmpl] add utility function to build a zip file

---

ci/maketmpl/md_image.go
ci/maketmpl/md_image_test.go

writing out md images with options to inline the image and/or inline the style that includes sizes.

[maketmpl] add md image writing

---

ci/auto-generate-readme.sh

no conversion result change; just better bash scripting.

[ci] refactor ci bash script

---

ci/maketmpl/util.go

not that we need to run on windows, but it is the right thing to do nonetheless

[maketmpl] perform filepath convertion

---

ci/maketmpl/builder.go
ci/maketmpl/builder_test.go
ci/maketmpl/template_meta.go
ci/maketmpl/testdata/configs/aws.yaml
ci/maketmpl/testdata/configs/gcp.yaml
ci/maketmpl/testdata/reefy-ray/README.md

it builds the zip file, the `ray-app.json` metadata file, and various flavors of readme markdown files..

[maketmpl] make template builder

---

configs/ray-summit-ai-libraries/aws.yaml
configs/ray-summit-core-masterclass/aws.yaml
configs/ray-summit-end-to-end-llms/aws.yaml
configs/ray-summit-multi-modal-search/aws.yaml
configs/ray-summit-rag/aws.yaml
configs/ray-summit-stable-diffusion/aws.yaml

Undo constrains on which zone to run post summit ODCR

remove set availability zones and enable cross-zone autoscaling

---

ci/maketmpl/build_all.go
ci/maketmpl/build_all_test.go
ci/maketmpl/testdata/BUILD.yaml
ci/maketmpl/testdata/fishy-ray/README.md

[maketmpl] add function that builds all templates defined

---

BUILD.yaml
ci/maketmpl/hello.go
ci/maketmpl/maketmpl/main.go

starts with workspace and job basic templates

[maketmpl] build for real in maketmpl binary

---

templates/e2e-llm-workflows/deploy/jobs/ft.yaml

This makes the Ray Data + Ray Train dashboard available for the template.
I tested it and made sure the model still gets high accuracy and can be served.

Update llmforge version for e2e LLM template

---

ci/go.mod
ci/go.sum

[maketmpl] upgrade golang compiler and libs

---

BUILD.yaml

[tmpls] add service intro template building 

---

configs/batch-llm/aws-l4.yaml
templates/ray-data-llm/README.ipynb
templates/ray-data-llm/README.md

* Need un-gated model to workaround https://github.com/ray-project/ray/pull/51508
* The template needs at most 5 CPU, which requires 2xlarge config
demo recording https://drive.google.com/file/d/1bxNNyLOdc9xNYoh9xFGcz2zXxfMrwQKI/view?usp=drive_link

[Data][LLM] Update model and workspace config for ray.data.llm template

---

templates/ray_serve_llm/README.ipynb
templates/ray_serve_llm/README.md

Re: https://github.com/anyscale/docs/pull/1210#discussion_r2007838407
Follow up on all template related changes to fix grammar and style issues

[Serve.llm] update ray serve llm template grammar and style

---

templates/ray-data-llm/README.ipynb
templates/ray-data-llm/README.md

[Data][LLM] update ray.data.llm notebook to apply style/typo suggestion

---

templates/intro-services/README.ipynb
templates/intro-services/README.md

Minor fixes on Intro to Services template based on feedback from Man Group

fix typo + add reminder on connectivity requirement

---

ci/go.mod
ci/go.sum

getting prepared for new release

[maketmpl] upgrade golang toolchain and libraries

---

ci/maketmpl/md_image.go
ci/maketmpl/md_image_test.go

so that it does not include things that do not belong to the img tag

[maketmpl] fix md image parse

---

BUILD.yaml
ci/maketmpl/md_image.go
ci/maketmpl/md_image_test.go

[tmpl] wrap entity-recognition-with-llms into release zip

---

templates/fine-tune-stable-diffusion/README.ipynb
templates/fine-tune-stable-diffusion/README.md

Pin version to fix import error:
```
ImportError: cannot import name 'cached_download' from 'huggingface_hub'
```
https://rootly.com/account/incidents/547-compassionate-ocean
Tested on a workspace.

[fine-tune-stable-diffusion] pin huggingface_hub

---

configs/batch-llm/aws-l4.yaml
configs/batch-llm/gce.yaml

https://anyscale1.atlassian.net/browse/LLM-2239
https://github.com/anyscale/templates/issues/442

[data.llm] Update template to avoid using head node for computation

---

templates/ray-data-llm/README.ipynb
templates/ray-data-llm/README.md

Key fixes:
1. Use S3 as a data source since HuggingFace Hub is typically unreliable.
2. Increase the concurrency to 4 to show how to do distributed processing properly on multiple GPUs
3. Fix errors for printing the responses
4. improve wording and descriptions on certain steps
Jira link:
https://anyscale1.atlassian.net/browse/LLM-2239?focusedCommentId=38163&sourceType=mention&atlOrigin=679a669cdd184eb49be713a093149b84

refactor and improve the templates with csv source, fix bugs, etc

---

templates/intro-services/README.ipynb
templates/intro-services/README.md

Reverts anyscale/templates#458, not needed anymore

Revert "Fix services template for Azure"

---

templates/ray-data-llm/README.ipynb
templates/ray-data-llm/README.md

This fixes some minor issues in the existing ray data llm template reported by @LindaHaviv

Some minor fixes in data llm template

---

templates/ray-data-multimodal-hol/README.md

add readme for ray-data-multimodal-hol
