anyscale/templates

templates/serve-stable-diffusion/README.md

use remote url for images so that workspace can render the images correctly while starting up.

use remote url for images

---

configs/text-embeddings/aws.yaml
configs/text-embeddings/gce.yaml

https://github.com/anyscale/templates/pull/67 created the `text-embeddings` workspace template with a bad config involving `custom_llm_gpu` which prevents satisfying the resource requirement. This PR fixes the issue by removing the unnecessary configuration, since autoscaling works across any of the GPU worker types by default.

Remove custom `custom_llm_gpu` resource specification for `text-embeddings` template

---

templates/fine-tune-llm/README.md
templates/fine-tune-llm/job_compute_configs/aws.yaml
templates/fine-tune-llm/job_compute_configs/gcp.yaml
templates/fine-tune-llm/train.py

Currently  we ask user to figure out cloud id (not even name). It is not obvious how to get it for most people. Since this is run from a workspace, we can automatically infer these.

finetune llm - automatically read cloud id and region

---

configs/text-embeddings/aws.yaml

This is to fix the instance type of embedding job. Otherwise the embedding job workspace cannot be launched.

Fix instance type of embedding aws.yaml

---

templates/endpoints/models/mistral/mistralai--Mistral-7B-Instruct-v0.1_a10g_tp1-lora.yaml

Forward fixes that https://github.com/anyscale/templates/pull/124 was missing the yaml.
I manually verified the fix by running the template with the yaml included in this PR and querying the model

Add MistralAI TL=1 LoRA config to APE template

---

templates/endpoints/CustomModels.md
templates/endpoints/models/llama/codellama--CodeLlama-34b-Instruct-hf_a100-40g_tp4.yaml
templates/endpoints/models/llama/meta-llama--Llama-2-13b-chat-hf_a100-40g_tp2.yaml
templates/endpoints/models/llama/meta-llama--Llama-2-70b-chat-hf_a100-40g_tp8.yaml
templates/endpoints/models/llama/meta-llama--Llama-2-70b-chat-hf_a100-80g_tp8.yaml
templates/endpoints/models/llama/meta-llama--Llama-2-7b-chat-hf_a10g_tp1.yaml
templates/endpoints/models/llama/meta-llama--Llama-2-7b-chat-hf_l4-lora.yaml
templates/endpoints/models/llama/meta-llama--Llama-2-7b-chat-hf_l4_tp1.yaml
templates/endpoints_v2/models/llama/codellama--CodeLlama-34b-Instruct-hf_a100-40g_tp4.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-13b-chat-hf_a100-40g_tp2.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-70b-chat-hf_a100-40g_tp8.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-70b-chat-hf_a100-80g_tp8.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-7b-chat-hf_a10g_tp1.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-7b-chat-hf_l4-lora.yaml
templates/endpoints_v2/models/llama/meta-llama--Llama-2-7b-chat-hf_l4_tp1.yaml

As discussed [here](https://anyscaleteam.slack.com/archives/C05N9KFPUR3/p1710374812717179), all llama 2 endpoints templates prompt formats are off. The ground truth can be found in RayLLM. In RayLLM, we test for "prompt format consistency with the following format:
```
llama2_prompt_format = PromptFormat(
system="<<SYS>>\n{instruction}\n<</SYS>>\n\n",
assistant=" {instruction} </s><s>",
trailing_assistant="",
user="[INST] {system}{instruction} [/INST]",
default_system_message="",
system_in_user=True,
)
```
https://github.com/anyscale/ray-llm/blob/9fb9f710dd717429c54968d1c23d2f7b60e7d8f9/tests/test_aviary/common/test_prompt_format_consistency.py#L4
This format is also aligned with llm-forge.
Only the endpoints templates are different.
CC @mjconnor @akshay-anyscale

Fix all prompt formats

---

templates/fine-tune-llm/README.md
templates/fine-tune-llm/main.py

- Fixed wandb api key insertion
- Basically llmforge auto adds the runtime env `WANDB_API_KEY` but if it's specified in `runtime_env`, it would be a conflict. So adding `RAY_OVERRIDE_JOB_RUNTIME_ENV ` as an override to make this workflow both work as a ray job (OA) and anyscale job (Platform)
- Customer issue: https://anyscaleteam.slack.com/archives/C0683S5GBJ7/p1710517651515999
- repro'ed example job: https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_d8wyn4f25fe5blrmpft27xlsnr

[FT-Template] Fixed wandb api key insertion

---

configs/endpoints_v2/aws.yaml
configs/endpoints_v2/gcp.yaml

* This is the only API that is compatible across existing backend + existing/new SDK.
* When new backend supports using `enable-cross-zone-scaling`, we will switch to that.

Switch to using `flags` for specifying multi-zone

---

templates/text-embeddings/README.ipynb
templates/text-embeddings/README.md
templates/text-embeddings/main.py
templates/text-embeddings/util/utils.py

- Instead of including the embeddings computation logic in the docker image, we instead copy the logic from `runtime` (https://github.com/anyscale/runtime/pull/507) into a local file used in the workspace. This way, the user can easily customize the logic for their own use case.
- Add section for Jobs, linking to the Intro to Jobs page.
Tested on [OA workspace](https://console.anyscale-staging.com/v2/cld_kvedZWag2qA8i5BjxUevf5i7/workspaces/expwrk_uw29mztdz8z5az79vmqitcraft/ses_9v1fkddrtlauygzndkreuues31?workspace-tab=vscode)

Update `text-embeddings` template

---

templates/text-embeddings/README.ipynb

- This syntax was causing failures here https://github.com/anyscale/endpoint-docs/actions/runs/8545480588/job/23413876496?pr=133

[OA] Fix unsupported markdown in endpoint docs

---

templates/intro-jobs/README.ipynb

When we submit jobs without an explicit name the prefix `job-` is prepended to the name of the workspace. In this case, the name of the Intro to Jobs workspace already starts with the `job-` prefix, so we submit a job with the name `job-job-...`. This PR changes the template to submit a job with the name `my-job` preventing the email from saying "Anyscale Job job-job-...".
Before:
After:

Adding in name to prevent Job job-job-... name

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md

Made an error merging before commiting the model revert, this PR changes the default model back to Mistral.

Revert `batch-llm` template default model back to Mistral

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md
templates/batch-llm/main.py
templates/batch-llm/util/utils.py

Refactor the Hugging Face token fetching mechanism used in `batch-llm` template so that the common utility function can also be used in the Python script used for job submission.
Tested on [workspace](https://console.anyscale-staging.com/v2/cld_kvedZWag2qA8i5BjxUevf5i7/workspaces/expwrk_ad2uga9wmqi393sjkguu11nnh7/ses_ww5pylrj6fqsfimlfn48g4mtwq?workspace-tab=vscode)

Update Hugging Face token fetching in `batch-llm` template

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md
templates/batch-llm/main.py
templates/text-embeddings/README.ipynb
templates/text-embeddings/README.md
templates/text-embeddings/main.py

Due to how the Anyscale Artifact Storage IAM policy is configured and how the PyArrow s3fs tries to create directories we were getting errors from these templates when we tried to write to the Anyscale Artifact Storage. More context on that issue [in slack here](https://anyscaleteam.slack.com/archives/C0695Q8TZSN/p1713828788038729). 
We plan to fix the behavior on the Ray Data side to by default not try to create directories for s3 as this call is not necessary, but for now this patch in the templates will resolve the issue while we wait for the next Ray release (will happen after the OA release).

Adding in try_create_dir=False to unblock OA release

---

templates/batch-llm/README.ipynb
templates/batch-llm/README.md
templates/batch-llm/main.py
templates/batch-llm/util/utils.py

This PR refines the logic in `batch-llm` workspace template for authenticatin Hugging Face token from user input. 
- Instead of relying on environment variable read from the file cached by Hugging Face, we copy the token to a local file in the working directory of the workspace template, which can be read by the job we launch later.
- Also replace the model config loading with a simpler HTTP request to their model registry, which serves as a check to see if the model requires a token.
- Move the token authentication to its own cell to denote importance
Also remove text related to tensor parallelism, since it is confusing for most non-advanced users without documentation (we currently don't have good documentation around this)

Refine Hugging Face token auth in `batch-llm` template

---

templates/intro-services/README.ipynb
templates/intro-services/README.md
templates/serve-stable-diffusion/README.ipynb
templates/serve-stable-diffusion/README.md

Moving to use the un-aliased `anyscale service deploy` because:
- Documentation/discovery is clearer (https://docs.endpoints.anyscale.com/preview/reference/service-api/)
- Matches other commands like `anyscale service status`
- Also works from outside of workspaces (where `serve deploy` won't because it's an alias)

s/serve deploy/anyscale service deploy

---

templates/intro-tune/README.ipynb
templates/intro-tune/filesystem_utils.py

Use `s3fs` instead of the default `pyarrow` `S3FileSystem`.
`ANYSCALE_ARTIFACT_STORAGE` uses a shared bucket.  The `pyarrow` implementation makes (unneeded) requests that require permissions that are (intentionally) not given.
A long term fix will be to remove these calls from the `pyarrow` imeplementation.

[parallel-experiments] use s3fs for s3 storage

---

templates/endpoints/models/llama/meta-llama--Meta-Llama-3-70B_a100-40g_tp8.yaml
templates/endpoints_v2/models/llama/meta-llama--Meta-Llama-3-70B_a100-40g_tp8.yaml

Llama 3 prompt format used in the example configs is incorrect. This is a tiny PR to fix the prompt format following the [official guide](https://github.com/meta-llama/llama-recipes)

Fix Llama 3 prompt format used in example deployment configs

---

templates/text-embeddings/README.ipynb
templates/text-embeddings/README.md

- Upgrade `langchain` to remove a pip dependency warning
- Resize image in notebook
Video walkthrough of template:
https://github.com/anyscale/templates/assets/5122851/b19f7293-a094-47bd-8a72-9a56b1807b23

Fix pip dependency and resize image in `text-embeddings` template

---

templates/text-embeddings/README.ipynb
templates/text-embeddings/README.md

Having the <center> tags makes the file break MDX file compatibility on the conversion from ipynb to mdx, which breaks the docs. Removing it for now, and if we need a more aesthetic screenshot, then we can follow-up in a separate PR.

Remove HTML <center> to comply with mdx

---

templates/fine-tune-llm_v2/README.ipynb
templates/fine-tune-llm_v2/README.md
templates/fine-tune-llm_v2/cookbooks/lora_vs_full_parameter/README.md

This is a tiny PR to fix `wandb` key export in the finetuning template. Currently, we exported the key through an iPython shell command `!export WANDB_API_KEY=xxx` . This, however, does not actually accomplish what we want, because training is launched with a separate shell command `!python main.py ...` . Each shell command gets executed in a different subshell, which means `WANDB_API_KEY` does not transfer over to the training script env. This PR fixes the issue by exporting env var through `os`.

Fix `wandb` API key export in finetuning template

---

templates/fine-tune-llm_v2/training_configs/full_param/llama-3-8b.yaml
templates/fine-tune-llm_v2/training_configs/lora/llama-3-8b.yaml

While releasing the 0.5.0.0 llm-forge image, we realized that we can some "_pytorch allocator cache flushes_" warnings.
According to pytorch, these slow down training and should be eliminated.
In some instances, they have also led to GPU OOMs.
Process behind this PR:
I launched every possible configuration (lora and full-parameter).
If the warning occured at the beginning, I'd let the training continue for a couple of iterations to see if we stabilize and the warning goes away. If it goes away, I didn't take action (in accordance with the pytorch warning message).
If the warning would occur from time to time, I'd reduce batch size.
I went through this process for all models and configurations to dogfood the template and see if this problem occurs elsewhere. The problem only occured for …

Update batch sizes for llama 3 8B to counter pytorch allocator cache flushes

---

configs/triton_services/aws.yaml
configs/triton_services/gce.yaml
templates/triton_services/README.md

Wrap model compile and upload in a ray actor to run on the GPU worker so we can remove the GPU head node dependency on this template. Also fix the configs. 
Full walkthrough video: https://drive.google.com/file/d/1HGOFNYneniECHuP4iX43_IsjiW9zYZRj/view?usp=sharing

[Triton] drop gpu header dependency

---

templates/fine-tune-llm_v2/README.ipynb
templates/fine-tune-llm_v2/README.md

A tiny PR to update `llmforge` versions table with the latest release (v0.5.2)

[ft-template] Update `llmforge` versions table with v0.5.2 release

---

templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/dpo-training/mistral_a10.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/dpo-training/mistral_a100.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/jobs/training/mistral_a10.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/jobs/training/mistral_a100.yaml

Updates DPO training configs for the right resource requests. With Ray, all gpu-based instances have `accelerator_type` custom resource value set to 1.  The recommended way is thus to  use something like `{"GPU": 1, "accelerator_type:A10G":  0.001}` instead of ` {"GPU": 1, "accelerator_type:A10G":  1}`  Because instances with 4xA10s and 1xA10s both have `{"accelerator_type:A10G":  1}` in the custom resource labels. This can thus give you a faulty allocation of nodes (even if you get 4 4xA10 nodes, you would have only satisfied "4" quantity of the custom resource `accelerator_type:A10G`, even if you have 16 GPUs i.e satisfy "16" for `GPU` resource).
Reference comment: https://github.com/ray-project/ray/pull/40286/files#r1361443657 
I'm also adding an override flag for the job config due to …

[ft-template] Update DPO training configs for the right resource requests

---

templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/README.ipynb
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/README.md
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/dpo-training/mistral_a10.yaml
templates/fine-tune-llm_v2/end-to-end-examples/fine-tune-preference/configs/dpo-training/mistral_a100.yaml

Updates DPO configs to use the correct format for resource requests. In `llmforge` 0.5.3, the custom resource requests  for the logprob processor are supposed to be named `worker_resources` while it has been changed to `custom_resources` in the latest master.

[ft-template] Update DPO configs to use older format

---

templates/e2e-llm-workflows/src/utils.py

writes to `/mnt/cluster_storage` instead since ray data could write the dataset to worker nodes

[Fix] Dataset upload from Ray Data

---

ci/maketmpl/util.go
ci/maketmpl/util_test.go

makes it possible to put a properly converted readme file into the built zip archive

[maketmpl] add support to save a different file or inlined bytes in zip

---

templates/fine-tune-llm_v2/deepspeed_configs/zero_2.json
templates/fine-tune-llm_v2/deepspeed_configs/zero_3_hpz.json
templates/fine-tune-llm_v2/training_configs/custom/meta-llama/Meta-Llama-3-70B/full/16xA100-80G-4k.yaml
templates/fine-tune-llm_v2/training_configs/custom/meta-llama/Meta-Llama-3-70B/lora/8xA100-80G-4k.yaml
templates/fine-tune-llm_v2/training_configs/custom/meta-llama/Meta-Llama-3-8B/lora/4xA10-512-mlflow.yaml
templates/fine-tune-llm_v2/training_configs/custom/meta-llama/Meta-Llama-3-8B/lora/4xA10-512-wandb.yaml
templates/fine-tune-llm_v2/training_configs/custom/meta-llama/Meta-Llama-3-8B/lora/4xA10-512.yaml
templates/fine-tune-llm_v2/training_configs/custom/meta-llama/Meta-Llama-Guard-2-8B/lora/llama-guard-2.yaml
templates/fine-tune-llm_v2/training_configs/custom/mistralai/mistral-7b/lora/4xA10-512.yaml

Edit template configs that do single node training with A10Gs to use ZeRO stage 2 - per new user guide on cluster shape + ZeRO stage recommendation.
WandB run for 4xA10G Llama-3-8B that works: https://wandb.ai/anyscale-llm-forge/llmforge/runs/jxg1sm1c
WandB run for 4xA10G Mistral-7B that works: https://wandb.ai/anyscale-llm-forge/llmforge/runs/rua1w3x2

[llms-finetuning] add zero_2 deepspeed config + modify templates for 4xA10 to request specific shape

---

templates/e2e-llm-workflows/README.ipynb
templates/e2e-llm-workflows/README.md
templates/e2e-llm-workflows/src/utils.py

- Remove potentially breaking `pip install -U anyscale`, since it's no longer needed.
- Automatically parse in the S3 bucket locations to the train config yaml

Remove some friction from e2e LLM template

---

templates/e2e-llm-workflows/README.ipynb

In https://github.com/anyscale/templates/commit/e635e7a98b0515aa45fba1bfb600f21877abb236, An unpinned `pip install -U anyscale` was added which broke after a later anyscale package release. 
The new endpoints image already comes with the latest anyscale installation so we can remove this now

Remove anyscale install from e2e llm template

---

templates/fine-tune-llm_v2/deepspeed_configs/zero_3_hpz.json
templates/fine-tune-llm_v2/deepspeed_configs/zero_3_offload_optim.json

since we're updating deepspeed version in https://github.com/anyscale/llm-forge/pull/511, need to update defaults that are no longer supported

[ft-template] remove stage3_prefetch_bucket_size 'auto' values since this is no longer supported

---

templates/e2e-dspy-workflow/README.ipynb
templates/e2e-dspy-workflow/README.md

Pins DSPy to the commit which adds the latest anyscale changes
Also moves the rng initialization to after ray.init

Pin DSPy to specific commit

---

templates/e2e-dspy-workflow/README.ipynb
templates/e2e-dspy-workflow/README.md
templates/e2e-dspy-workflow/configs/job.yaml
templates/e2e-llm-workflows/deploy/jobs/ft.yaml
templates/fine-tune-llm_v2/training_configs/custom/meta-llama/Meta-Llama-3-8B/lora/4xA10-512-liger.yaml
templates/llm-router/README.ipynb
templates/llm-router/README.md
templates/llm-router/configs/ft_config_a10.yaml
templates/llm-router/src/clear_cell_nums.py

Updates workspace templates after v0.5.8 release of `llmforge` . Product release has happened already so this PR can be safely merged. 
Some important changes in this version:
- `checkpoint_every_n_epochs` is deprecated in favour of `checkpoint_and_evaluation_frequency`
- `max_num_checkpoints` is deprecated. 
- `awsv2` -> `aws` in `RemoteStoragePath`. This is because of awsv2 cli deprecation. Since RemoteStoragePath is a bleeding edge feature, this is hard deprecation. 
- `TorchCompileConfig` is here. 
Also, we added liger support in the previous release - 0.5.7 but that was not added until now. This PR also adds liger to our configs. 
FWIW, torch compile + liger has some subtleties around compatibility - the best configuration for perf is turning on all liger flags, so this PR only adds …

Update templates after v0.5.8 `llmforge` release 

---

templates/fine-tune-llm_v2/README.ipynb
templates/fine-tune-llm_v2/README.md

Tiny PR to fix a hyperlink. `LLMForge` should point to the intro page in the docs rather than the versions table.

Change hyperlink for llmforge to docs instead of versions table

---

templates/ray-data-llm/README.ipynb
templates/ray-data-llm/README.md

Issue: https://github.com/anyscale/templates/issues/442
At the moment the processing rate is ~5 rows/s, so processing 1.44M rows will take 80 hours. Limiting it to 10k rows lowers processing time to ~0.5 hours, which is better UX.

[data][llm] Limit input data size to 10k

---

templates/fine-tune-llm-oss/README.ipynb
templates/fine-tune-llm-oss/README.md

It's too small right now - make it bigger

[llm-finetuning] increase image size on template
